### ISSUE TITLE
How to run the application?

### ISSUE THREAD

**Issue by laaksonel** [kubinio123/streams-app#1]
Hi,
How is the project supposed to be run?
I tried first to run `create-topics.sh` inside `tools` container because all the kafka tools are available there.
However topic creations failed because of missing parameter `Missing required argument "[replication-factor]"`
Additionally, there is no `sbt` installed in `tools` container so running `avro` project inside `tools` fails.

Am I completely lost?

**Comment by kubinio123** [comment]
Hi, thanks for the report. Let me add a README instruction on how to run the example.

**Comment by kubinio123** [comment]
Could you take a look at the instructions I added - https://github.com/kubinio123/streams-app/pull/2, are they understandable? I assumed that `sbt` will be installed on your OS. Other option will be to use a docker container with `sbt` and mount the project directory there, but I thought that people will rather want to run this thru IDE to easily tweak and modify.

**Comment by laaksonel** [comment]
I managed to run the app with your instructions in README, but I had to do some tweaking (comments in the PR).
Anyway, I want to thank you for sharing this Kafka demo and for excellent blog post you've written. I hope you keep posting.

**Comment by kubinio123** [comment]
@laaksonel thank you also for the great feedback and help with adding the "how to run" instructions. Honestly I kinda forgot about taking care of that. Take care! 😃
